### ISSUE TITLE
Make logging in for feature tests more robust

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#889]
When we started adding feature tests we weren't sure how best to simulate logging in.

The [appropriate body tests use OTP](https://github.com/DFE-Digital/register-early-career-teachers/blob/main/spec/support/features/user_helper.rb#L16) and the school reg tests (soon, after #859) are going to use personas.

The persona approach makes more sense but with persona users being tied to `User` accounts, the setup isn't entirely robust as the school name needs to be in the persona name.

```
  def sign_in_as_school_user
    FactoryBot.create(:school, gias_school: FactoryBot.build(:gias_school, name: "Abbey Grove School"))

    FactoryBot.create(:user, email: "bob.belcher@example.com", name: "Bob Belcher (Abbey Grove School)").tap do |_user|
      sign_in_as_persona('Bob Belcher')
    end
  end
```

This 'link' also means we need to jump through extra hoops in the seeds and [in the personas helper](https://github.com/DFE-Digital/register-early-career-teachers/blob/main/app/helpers/personas_helper.rb).

I think we can make this easier by hardcoding personas in a `config/personas.yml` file

```yaml
---
- name: Velma Dinkley
  appropriate_body: Golden Leaf Academy
  email: velma@example.com
  image: personas/velma.png
- name: Selma Moon
  school: Brookfield School
  email: selma@example.com
  image: personas/selma.png
- name: Norville Rogers
  dfe: true
  email: shaggy@example.com
  image: personas/shaggy.png
```

The one bit that needs to line up with seed data is the name of the `appropriate_body` or `school`. We can verify that's the case and log (or raise) an error in an initializer when running the app while personas are enabled.

In the tests, when using a persona we can simply create an appropriate body or school based on the name.

## Switch the personas over to a hardcoded list

* [ ] Remove the seeds and add a personas config file
* [ ] Rename the `developer` provider name to `persona` in `config/initializers/omniauth.rb`
* [ ] Remove the Persona model and add a Persona service which loads the yaml file and lists the personas. If [personas are disabled](https://github.com/DFE-Digital/register-early-career-teachers/blob/main/config/application.rb#L34) this should return nothing.
* [ ] Update the user helper accordingly and switch the appropriate body and school methods over to the new approach
